### ISSUE TITLE
ExpectationError: Unexpected call

### ISSUE THREAD

**Issue by soupman99** [gaguirre/sinon-mongoose#4]
I'm running into an issue.  I'm using supertest to do some full route testing, the issue is when I try and mock out my mongoose model in a before() function I run into this error.  I think my mongoose model never actually get swapped out with the mock.

The weird thing is, when I run each test individually it all works fine, but when I try and run in a sequence it bunch start to fail.  Any ideas?

```
var     should = require('should'),
        sinon = require("sinon"),
        request = require('supertest'),
        path = require('path'),
        mongoose = require('mongoose'),
        User = mongoose.model('User'),
        Business = mongoose.model('Business'),
        express = require(path.resolve('./config/lib/express'));

        require('sinon-mongoose');

var mockBusiness = {title:"Joe's"}

describe('Order CRUD tests', function () {

    before(function (done) {

        // Get application
        app = express.init(mongoose);
        agent = request.agent(app);

        sinon.mock(Business)
            .expects('findByIdAndUpdate')
            .chain('lean')
            .chain('exec')
            .yields(null, mockBusiness);

        done();
    });

    it('should be able to do stuff', function (done) {
        //......
        //......
        done();
    });

});

```

**Comment by soupman99** [comment]
After further investigation I think the issue is, the method in the mock is getting called with my first test. When my subsequent tests call the same method thats whats causing the error.  Is there a way to specify how many times I expect the method to be called?  I played around with it and couldn't figure it out since sinon.mock is being replaced by your method.

**Comment by soupman99** [comment]
I figured it out.  Didn't realize the examples could be so helpful ;)

**Comment by gaguirre** [comment]
@soupman99 good to hear your issue is solved :)
Based on the code you posted it, I guess you did it creating the expectations within each test definition (i.e. each `it`), right?
